# Generated by Django 2.2.2 on 2019-07-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(unique=True)),
                ('sna', models.TextField()),
                ('tot', models.IntegerField()),
                ('sarea', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('ar', models.TextField()),
                ('sareaen', models.TextField()),
                ('snaen', models.TextField()),
                ('aren', models.TextField()),
                ('act', models.BooleanField()),
            ],
            options={
                'ordering': ['-sno'],
            },
        ),
        migrations.CreateModel(
            name='UbikeStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(unique=True)),
                ('sna', models.TextField()),
                ('tot', models.IntegerField()),
                ('sbi', models.IntegerField()),
                ('sarea', models.TextField()),
                ('mday', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('ar', models.TextField()),
                ('sareaen', models.TextField()),
                ('snaen', models.TextField()),
                ('aren', models.TextField()),
                ('bemp', models.IntegerField()),
                ('act', models.BooleanField()),
            ],
            options={
                'ordering': ['-sno'],
            },
        ),
    ]
