# Generated by Django 2.2.2 on 2019-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField()),
                ('mday', models.DateTimeField()),
            ],
            options={
                'ordering': ['-num'],
            },
        ),
        migrations.AddField(
            model_name='ubikestop',
            name='num',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubikestop',
            name='sno',
            field=models.IntegerField(),
        ),
    ]
