# Generated by Django 2.2.2 on 2019-07-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0002_auto_20190702_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('locationName', models.TextField()),
                ('stationId', models.TextField()),
                ('obsTime', models.DateTimeField()),
                ('elementName', models.FloatField()),
                ('ELEV', models.FloatField()),
                ('RAIN', models.FloatField()),
                ('MIN_10', models.FloatField()),
                ('HOUR_3', models.FloatField()),
                ('HOUR_6', models.FloatField()),
                ('HOUR_12', models.FloatField()),
                ('HOUR_24', models.FloatField()),
                ('NOW', models.FloatField()),
                ('latest_2days', models.FloatField()),
                ('latest_3days', models.FloatField()),
                ('CITY', models.TextField()),
                ('CITY_SN', models.IntegerField()),
                ('TOWN', models.TextField()),
                ('TOWN_SN', models.IntegerField()),
                ('ATTRIBUTE', models.TextField()),
            ],
            options={
                'ordering': ['-stationId'],
            },
        ),
        migrations.CreateModel(
            name='AutoRainStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('locationName', models.TextField()),
                ('stationId', models.TextField()),
                ('CITY', models.TextField()),
                ('CITY_SN', models.IntegerField()),
                ('TOWN', models.TextField()),
                ('TOWN_SN', models.IntegerField()),
                ('ATTRIBUTE', models.TextField()),
            ],
            options={
                'ordering': ['-stationId'],
            },
        ),
        migrations.CreateModel(
            name='AutoWeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('locationName', models.TextField()),
                ('stationId', models.TextField()),
                ('obsTime', models.DateTimeField()),
                ('ELE', models.FloatField()),
                ('WDIR', models.FloatField()),
                ('WDSD', models.FloatField()),
                ('TEMP', models.FloatField()),
                ('HUMD', models.FloatField()),
                ('PRES', models.FloatField()),
                ('SUN', models.FloatField()),
                ('H_24R', models.FloatField()),
                ('H_FX', models.FloatField()),
                ('H_XD', models.FloatField()),
                ('H_FXT', models.FloatField()),
                ('D_TX', models.FloatField()),
                ('D_TXT', models.FloatField()),
                ('D_TN', models.FloatField()),
                ('D_TNT', models.FloatField()),
                ('CITY', models.TextField()),
                ('CITY_SN', models.FloatField()),
                ('TOWN', models.TextField()),
                ('TOWN_SN', models.FloatField()),
            ],
            options={
                'ordering': ['-stationId'],
            },
        ),
        migrations.CreateModel(
            name='AutoWeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('locationName', models.TextField()),
                ('stationId', models.TextField()),
                ('CITY', models.TextField()),
                ('CITY_SN', models.IntegerField()),
                ('TOWN', models.TextField()),
                ('TOWN_SN', models.IntegerField()),
            ],
            options={
                'ordering': ['-stationId'],
            },
        ),
        migrations.CreateModel(
            name='BureauWeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('locationName', models.TextField()),
                ('stationId', models.TextField()),
                ('obsTime', models.DateTimeField()),
                ('ELEV', models.FloatField()),
                ('WDIR', models.FloatField()),
                ('WDSD', models.FloatField()),
                ('TEMP', models.FloatField()),
                ('HUMD', models.FloatField()),
                ('PRES', models.FloatField()),
                ('R24R', models.FloatField()),
                ('H_FX', models.FloatField()),
                ('H_XD', models.FloatField()),
                ('H_FXT', models.FloatField()),
                ('H_F10', models.FloatField()),
                ('H_10D', models.FloatField()),
                ('H_F10T', models.FloatField()),
                ('H_UVI', models.FloatField()),
                ('D_TX', models.FloatField()),
                ('D_TXT', models.FloatField()),
                ('D_TN', models.FloatField()),
                ('D_TNT', models.FloatField()),
                ('D_TS', models.FloatField()),
                ('H_VIS', models.FloatField()),
                ('H_Weather', models.TextField()),
                ('CITY', models.TextField()),
                ('CITY_SN', models.IntegerField()),
                ('TOWN', models.TextField()),
                ('TOWN_SN', models.IntegerField()),
            ],
            options={
                'ordering': ['-stationId'],
            },
        ),
        migrations.CreateModel(
            name='BureauWeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('locationName', models.TextField()),
                ('stationId', models.TextField()),
                ('CITY', models.TextField()),
                ('CITY_SN', models.IntegerField()),
                ('TOWN', models.TextField()),
                ('TOWN_SN', models.IntegerField()),
            ],
            options={
                'ordering': ['-stationId'],
            },
        ),
        migrations.CreateModel(
            name='FetchAutoRainDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField()),
                ('mday', models.DateTimeField()),
            ],
            options={
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='FetchAutoWeatherDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField()),
                ('mday', models.DateTimeField()),
            ],
            options={
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='FetchBureauWeatherDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField()),
                ('mday', models.DateTimeField()),
            ],
            options={
                'ordering': ['-num'],
            },
        ),
        migrations.RenameModel(
            old_name='FetchDataRecord',
            new_name='FetchUbikeDataRecord',
        ),
    ]
