# Generated by Django 2.2.2 on 2019-07-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0004_auto_20190722_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoweatherdata',
            old_name='ELE',
            new_name='ELEV',
        ),
    ]
